(window.CURRICULUM_MODULES = window.CURRICULUM_MODULES || []).push({
  id: 'i2ctb4',
  title: 'Controller FSM Testbenches',
  icon: '🎛️',
  level: 'intermediate',
  lessons: [

    // ─────────────────────────────────────────────────────────────────────
    // L1 — Testing the Address Phase  (Tier 3)
    // ─────────────────────────────────────────────────────────────────────
    {
      id: 'i2ctb4l1',
      title: 'L1 — Testing the Address Phase',
      theory: `
<h2>Where this fits in real hardware verification</h2>
<p>Linux kernel developers who add a new I²C peripheral driver run exactly this test before merging: they stimulate the address phase, confirm that the correct device acknowledges, and then confirm that a wrong address produces a NACK. A single bug here causes every I²C transaction on the bus to fail silently. This chapter shows you how to write that test in SystemVerilog.</p>

<h2>What the address phase looks like on the wire</h2>
<pre class="code-block">START  A6  A5  A4  A3  A2  A1  A0  R/W  ACK
  |    |   |   |   |   |   |   |   |    |
SCL: _  ‾‾  _‾  _‾  _‾  _‾  _‾  _‾  _‾  _‾  _
SDA: 1↘0  b6  b5  b4  b3  b2  b1  b0  rw  ↑ACK↓

  9 SCL clock cycles total after the START pulse.
  Cycle 9 = ACK slot: target pulls SDA low (ACK) or releases (NACK).
</pre>

<h2>Transaction-level tasks — the core concept</h2>
<p>A <strong>transaction-level task</strong> hides the bit-by-bit SCL/SDA toggling behind a single reusable call. Think of it like a function in software: you describe the sequence once, then call it with different arguments for each test scenario. The task <code>do_address_phase(addr, rw, ack)</code> drives START, then 7 address bits MSB-first, then the R/W bit, then simulates the target's ACK or NACK response on the 9th clock cycle.</p>

<pre class="code-block">task automatic do_address_phase(
  input logic [6:0] addr,
  input logic       rw,
  input logic       ack_response   // 0=ACK, 1=NACK (from target's perspective)
);
  // drive START: SCL high, SDA falls
  // send 7 addr bits MSB first, then rw bit
  // on 9th cycle: simulate target pulling SDA low for ACK
  // sample addr_ack and done after 9th posedge clk
endtask</pre>

<table class="truth-table">
  <tr><th>Scenario</th><th>addr</th><th>rw</th><th>ack_response</th><th>Expected addr_ack</th><th>Expected done</th></tr>
  <tr><td>Correct address, ACK</td><td>7'h48</td><td>0</td><td>0 (pulled low)</td><td>1</td><td>1</td></tr>
  <tr><td>Wrong address, NACK</td><td>7'h50</td><td>0</td><td>1 (released)</td><td>0</td><td>1</td></tr>
</table>

<h2>Before you code</h2>
<p>You are writing a testbench for <code>i2c_addr_phase</code>. The module drives SCL and SDA during the 9-clock address window. Your testbench drives the input controls (<code>start</code>, <code>addr</code>, <code>rw</code>) and — crucially — drives back the simulated target's ACK on the SDA inout wire during the 9th SCL cycle. After each scenario you check <code>addr_ack</code> and <code>done</code>. A passing run prints two PASS lines followed by "Address phase testbench works!".</p>

<table class="truth-table">
  <tr><th>Port</th><th>Direction</th><th>Purpose</th></tr>
  <tr><td><code>clk</code></td><td>input logic</td><td>System clock — drives all flip-flops in the module.</td></tr>
  <tr><td><code>rst</code></td><td>input logic</td><td>Synchronous active-low reset — returns FSM to IDLE.</td></tr>
  <tr><td><code>start</code></td><td>input logic</td><td>Pulse high for one cycle to begin the address phase.</td></tr>
  <tr><td><code>addr</code></td><td>input logic [6:0]</td><td>Seven-bit target address to send MSB first.</td></tr>
  <tr><td><code>rw</code></td><td>input logic</td><td>Direction bit: 0 = write, 1 = read, sent after the 7 address bits.</td></tr>
  <tr><td><code>sda</code></td><td>inout wire</td><td>Bidirectional I²C data line — testbench drives it during the ACK slot.</td></tr>
  <tr><td><code>scl</code></td><td>output logic</td><td>I²C clock output generated by the module.</td></tr>
  <tr><td><code>addr_ack</code></td><td>output logic</td><td>Goes high when target pulled SDA low during the ACK clock cycle.</td></tr>
  <tr><td><code>done</code></td><td>output logic</td><td>Pulses high for one cycle when the 9-clock address phase completes.</td></tr>
</table>

<p><strong>Ready?</strong> Switch to the Code tab and type the module. Stuck? Tap 💡 Show Hint for an annotated reference.</p>
      `,
      tasks: [
        'Code tab is blank — type every line.',
        'Declare the tb module with timescale 1ns/1ps',
        'Declare wire sda and pullup pu(sda) — inout requires wire, not logic',
        'Declare logic clk=0 with always #5 clk=~clk for a 100 MHz clock',
        'Declare logic signals: rst, start, rw, addr_ack, done; logic [6:0] addr; logic scl',
        'Declare logic ack_drive and assign sda = ack_drive ? 1\'bz : 1\'b0 to simulate target ACK/NACK',
        'Instantiate i2c_addr_phase as dut, connecting all ports',
        'Write task automatic do_address_phase(addr, rw, ack_response): pulse start, wait for done, drive ack_drive on 9th SCL cycle',
        'Test scenario 1: addr=7\'h48, rw=0, ACK (ack_drive=0) — check addr_ack===1 and done===1',
        'Test scenario 2: addr=7\'h50, rw=0, NACK (ack_drive=1) — check addr_ack===0',
        'Print "Address phase testbench works!" and $finish',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 2 PASS lines should appear in the Output tab',
      ],
      hint:
`\`timescale 1ns/1ps
module tb;
  // --- clock ---
  logic clk = 0;
  always #5 clk = ~clk;   // 100 MHz system clock

  // --- inout SDA bus ---
  wire  sda;               // inout must be wire in testbench
  pullup pu(sda);          // models the physical pull-up resistor

  // --- DUT signals ---
  logic       rst, start, rw, addr_ack, done;
  logic [6:0] addr;
  logic       scl;

  // --- testbench drives ACK/NACK into the SDA line during ACK slot ---
  logic ack_drive;         // 1 = release (NACK), 0 = pull low (ACK)
  assign sda = ack_drive ? 1'bz : 1'b0;

  i2c_addr_phase dut (
    .clk     (clk),
    .rst     (rst),
    .start   (start),
    .addr    (addr),
    .rw      (rw),
    .sda     (sda),
    .scl     (scl),
    .addr_ack(addr_ack),
    .done    (done)
  );

  // do_address_phase: pulses start, waits 9 SCL cycles,
  // drives ack_response on the 9th cycle, then samples results
  task automatic do_address_phase(
    input logic [6:0] a,
    input logic       r,
    input logic       ack_resp   // 0 = ACK (pull low), 1 = NACK (release)
  );
    addr = a; rw = r; ack_drive = 1;  // release bus initially
    start = 1; @(posedge clk); #1; start = 0;
    // wait for FSM to begin; give it 9 SCL clocks (each SCL cycle = 2 clk periods)
    repeat(16) @(posedge clk); #1;
    ack_drive = ack_resp;              // apply ACK/NACK on the 9th SCL cycle
    repeat(4) @(posedge clk); #1;     // let DUT sample the ACK slot
  endtask

  initial begin
    $display("=== Address Phase Test ===");
    rst = 0; start = 0; addr = 0; rw = 0; ack_drive = 1;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    // Scenario 1: correct address + ACK
    do_address_phase(7'h48, 1'b0, 1'b0);
    if (addr_ack === 1)
      $display("PASS  ACK received: addr_ack=1");
    else
      $display("FAIL  ACK received: addr_ack=%0b (expected 1)", addr_ack);

    repeat(2) @(posedge clk); #1;

    // Scenario 2: wrong address, NACK
    do_address_phase(7'h50, 1'b0, 1'b1);
    if (addr_ack === 0)
      $display("PASS  NACK: addr_ack=0");
    else
      $display("FAIL  NACK: addr_ack=%0b (expected 0)", addr_ack);

    $display("Address phase testbench works!");
    $finish;
  end
endmodule`,
      design:
`// Type the i2c_addr_phase testbench here.
// See Theory for the transaction-level task concept.
//
// Ports to declare (testbench signals):
//   wire  sda           -- inout: use wire + pullup pu(sda)
//   logic clk           -- 100 MHz clock with always #5 clk=~clk
//   logic rst, start, rw, addr_ack, done
//   logic [6:0] addr
//   logic scl
//   logic ack_drive     -- drives ACK (0) or NACK (z) into SDA
//
// Task: do_address_phase(addr, rw, ack_response)
//   Pulse start, wait 9 SCL cycles, drive ack_drive, sample outputs.
//
// Delete this and start typing:
`,
      testbench:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;

  wire  sda;
  pullup pu(sda);

  logic       rst, start, rw, addr_ack, done;
  logic [6:0] addr;
  logic       scl;
  logic       ack_drive;
  assign sda = ack_drive ? 1'bz : 1'b0;

  i2c_addr_phase dut (
    .clk(clk), .rst(rst), .start(start),
    .addr(addr), .rw(rw), .sda(sda), .scl(scl),
    .addr_ack(addr_ack), .done(done)
  );

  task automatic do_address_phase(
    input logic [6:0] a,
    input logic       r,
    input logic       ack_resp
  );
    addr = a; rw = r; ack_drive = 1;
    start = 1; @(posedge clk); #1; start = 0;
    repeat(16) @(posedge clk); #1;
    ack_drive = ack_resp;
    repeat(4) @(posedge clk); #1;
  endtask

  initial begin
    $display("=== Address Phase Test ===");
    rst = 0; start = 0; addr = 0; rw = 0; ack_drive = 1;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    do_address_phase(7'h48, 1'b0, 1'b0);
    if (addr_ack === 1)
      \$display("PASS  ACK received: addr_ack=1");
    else
      \$display("FAIL  ACK received: addr_ack=%0b (expected 1)", addr_ack);

    repeat(2) @(posedge clk); #1;

    do_address_phase(7'h50, 1'b0, 1'b1);
    if (addr_ack === 0)
      \$display("PASS  NACK: addr_ack=0");
    else
      \$display("FAIL  NACK: addr_ack=%0b (expected 0)", addr_ack);

    \$display("Address phase testbench works!");
    \$finish;
  end
endmodule`,
      expected: [
        'PASS  ACK received: addr_ack=1',
        'PASS  NACK: addr_ack=0',
        'Address phase testbench works!'
      ]
    },

    // ─────────────────────────────────────────────────────────────────────
    // L2 — Testing the Data Phase  (Tier 3)
    // ─────────────────────────────────────────────────────────────────────
    {
      id: 'i2ctb4l2',
      title: 'L2 — Testing the Data Phase',
      theory: `
<h2>Why the data phase matters to real engineers</h2>
<p>Every I²C payload — the command register you write to a temperature sensor, the configuration byte you push to an OLED driver, the bytes you read back from a EEPROM — travels through the data phase. It is also the widest window for bugs: one bit arriving in the wrong order corrupts the entire message, yet the bus keeps running with no error signal. Verification teams test multi-byte sequences explicitly to catch shift-register misalignment, off-by-one bit counts, and incorrect NACK handling on the last byte.</p>

<h2>Data phase timing — 3-byte TX example</h2>
<pre class="code-block">Byte 1            Byte 2            Byte 3
D7 D6 D5 D4 D3 D2 D1 D0 ACK  D7 D6 D5 D4 D3 D2 D1 D0 ACK  D7...D0 NACK
|                          |                              |
SCL pulses continuously; SDA changes while SCL is low.
On the 9th pulse of each byte: target drives SDA=0 for ACK, releases for NACK.
</pre>

<h2>Multi-byte loop — the new concept</h2>
<p>A single <code>send_byte</code> task handles one 8-bit transfer. For a multi-byte sequence you call it in a loop, passing each byte in order. The key rule: ACK is expected after every byte <em>except</em> the last one in a read transaction (the master sends NACK to tell the target "I have all the data I need, stop sending"). You verify each ACK/NACK response individually.</p>

<pre class="code-block">// Parameterised N-byte TX: call send_byte for each byte
task automatic send_byte(input logic [7:0] data, input logic ack_resp);
  // drive 8 bits MSB-first on sda while scl is low
  // on 9th cycle: ack_resp selects ACK(0) or NACK(1)
endtask

// 3-byte sequence:
send_byte(8'hA1, 1'b0);  // byte 1, ACK expected
send_byte(8'hB2, 1'b0);  // byte 2, ACK expected
send_byte(8'hC3, 1'b1);  // byte 3, NACK (last byte)
</pre>

<table class="truth-table">
  <tr><th>Scenario</th><th>Bytes</th><th>ACK after each</th><th>Expected output</th></tr>
  <tr><td>3-byte TX</td><td>0xA1, 0xB2, 0xC3</td><td>ACK, ACK, NACK</td><td>tx_count===3, tx_done===1</td></tr>
  <tr><td>2-byte RX</td><td>0x55, 0xAA</td><td>ACK (byte 1), NACK (byte 2)</td><td>data_out[0]===0x55, data_out[1]===0xAA</td></tr>
</table>

<h2>Before you code</h2>
<p>You are writing a testbench for <code>i2c_data_phase</code>. The module drives or samples 8-bit bytes over SDA with SCL. Your testbench provides a <code>send_byte</code> task that drives each bit MSB-first on SDA while SCL toggles, then simulates an ACK or NACK response. For the RX test you drive known bits into SDA and verify the received bytes. A passing run prints three PASS lines followed by "Data phase testbench works!".</p>

<table class="truth-table">
  <tr><th>Port</th><th>Direction</th><th>Purpose</th></tr>
  <tr><td><code>clk</code></td><td>input logic</td><td>System clock driving all FSM flip-flops.</td></tr>
  <tr><td><code>rst</code></td><td>input logic</td><td>Synchronous active-low reset returning FSM to IDLE.</td></tr>
  <tr><td><code>mode</code></td><td>input logic</td><td>0 = TX (master sends), 1 = RX (master receives).</td></tr>
  <tr><td><code>start</code></td><td>input logic</td><td>Pulse high to begin the data phase transaction.</td></tr>
  <tr><td><code>n_bytes</code></td><td>input logic [3:0]</td><td>Number of bytes to transfer (1–8).</td></tr>
  <tr><td><code>tx_data</code></td><td>input logic [7:0]</td><td>Byte to transmit on the current iteration.</td></tr>
  <tr><td><code>sda</code></td><td>inout wire</td><td>Bidirectional I²C data line.</td></tr>
  <tr><td><code>scl</code></td><td>output logic</td><td>I²C clock output driven by the module.</td></tr>
  <tr><td><code>rx_data</code></td><td>output logic [7:0]</td><td>Byte received on the current iteration.</td></tr>
  <tr><td><code>byte_done</code></td><td>output logic</td><td>Pulses high for one cycle after each byte completes.</td></tr>
  <tr><td><code>done</code></td><td>output logic</td><td>Pulses high when all n_bytes have transferred.</td></tr>
</table>

<p><strong>Ready?</strong> Switch to the Code tab and type the module. Stuck? Tap 💡 Show Hint for an annotated reference.</p>
      `,
      tasks: [
        'Code tab is blank — type every line.',
        'Declare tb with timescale, wire sda, pullup pu(sda), and 100 MHz clock',
        'Declare DUT signals: rst, mode, start, n_bytes [3:0], tx_data [7:0], scl, rx_data [7:0], byte_done, done',
        'Declare logic sda_drive and tri-state driver: assign sda = sda_drive_en ? (sda_drive ? 1\'bz : 1\'b0) : 1\'bz',
        'Instantiate i2c_data_phase as dut, connecting all ports',
        'Write task automatic send_byte(data, ack_resp): drive 8 bits MSB-first on SDA each SCL low period, drive ack_resp on 9th cycle, wait for byte_done',
        'Write task automatic recv_byte(expected): drive known bits on SDA while SCL is high, verify rx_data===expected after byte_done',
        'Test 1: 3-byte TX (0xA1, 0xB2, 0xC3); ACK after bytes 1 and 2, NACK after byte 3 — check done===1',
        'Test 2: 2-byte RX — drive 0x55 and 0xAA as SDA bits, verify rx_data matches each byte',
        'Print "Data phase testbench works!" and $finish',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 3 PASS lines should appear in the Output tab',
      ],
      hint:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;  // 100 MHz

  wire  sda;
  pullup pu(sda);

  logic       rst, mode, start, byte_done, done;
  logic [3:0] n_bytes;
  logic [7:0] tx_data, rx_data;
  logic       scl;

  // testbench drives SDA when it needs to inject bits or ACK/NACK
  logic sda_tb;   // 1 = release (high via pullup), 0 = pull low
  assign sda = sda_tb ? 1'bz : 1'b0;

  i2c_data_phase dut (
    .clk      (clk),
    .rst      (rst),
    .mode     (mode),
    .start    (start),
    .n_bytes  (n_bytes),
    .tx_data  (tx_data),
    .sda      (sda),
    .scl      (scl),
    .rx_data  (rx_data),
    .byte_done(byte_done),
    .done     (done)
  );

  // send_byte: drive 8 data bits MSB-first on SDA while SCL is low,
  // then drive ack_resp on the 9th (ACK) cycle.
  task automatic send_byte(input logic [7:0] data, input logic ack_resp);
    integer i;
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = data[i] ? 1'b1 : 1'b0;   // 1=release, 0=drive low
    end
    // 9th clock: ACK slot — target drives low for ACK
    @(negedge scl); #1;
    sda_tb = ack_resp;   // 0=ACK (pull low), 1=NACK (release)
    @(posedge byte_done); #1;
    sda_tb = 1;          // release after ACK
  endtask

  // recv_byte: drive known bits MSB-first so DUT can sample them on SCL posedge
  task automatic recv_byte(
    input logic [7:0] expected,
    input logic       send_ack  // 0=master ACKs (more to come), 1=master NACKs (last)
  );
    integer i;
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = expected[i] ? 1'b1 : 1'b0;
    end
    // master drives ACK/NACK on 9th cycle (master is the receiver here)
    @(negedge scl); #1;
    sda_tb = send_ack;   // 0=master ACKs, 1=master NACKs
    @(posedge byte_done); #1;
    sda_tb = 1;
    if (rx_data === expected)
      \$display("PASS  received 0x%02h", expected);
    else
      \$display("FAIL  received 0x%02h (expected 0x%02h)", rx_data, expected);
  endtask

  initial begin
    \$display("=== Data Phase Test ===");
    rst = 0; sda_tb = 1; mode = 0; start = 0; n_bytes = 0;
    tx_data = 0;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    // --- Test 1: 3-byte TX ---
    mode = 0; n_bytes = 4'd3;
    start = 1; @(posedge clk); #1; start = 0;
    tx_data = 8'hA1; send_byte(8'hA1, 1'b0);  // ACK
    tx_data = 8'hB2; send_byte(8'hB2, 1'b0);  // ACK
    tx_data = 8'hC3; send_byte(8'hC3, 1'b1);  // NACK (last byte)
    @(posedge done); #1;
    \$display("PASS  3 bytes transmitted");

    repeat(4) @(posedge clk); #1;

    // --- Test 2: 2-byte RX ---
    mode = 1; n_bytes = 4'd2;
    start = 1; @(posedge clk); #1; start = 0;
    recv_byte(8'h55, 1'b0);   // byte 1: master ACKs
    recv_byte(8'hAA, 1'b1);   // byte 2: master NACKs (last)
    @(posedge done); #1;
    \$display("PASS  2 bytes received");

    \$display("Data phase testbench works!");
    \$finish;
  end
endmodule`,
      design:
`// Type the i2c_data_phase testbench here.
// See Theory for the multi-byte loop concept.
//
// Ports to declare (testbench signals):
//   wire  sda               -- inout: use wire + pullup pu(sda)
//   logic clk               -- 100 MHz clock
//   logic rst, mode, start  -- control inputs
//   logic [3:0] n_bytes     -- number of bytes (1-8)
//   logic [7:0] tx_data     -- byte to transmit
//   logic scl               -- SCL output from DUT
//   logic [7:0] rx_data     -- byte received from DUT
//   logic byte_done, done   -- completion signals
//   logic sda_tb            -- testbench SDA driver
//
// Tasks:
//   send_byte(data, ack_resp) -- drive 8 bits + ACK slot, wait for byte_done
//   recv_byte(expected, ack)  -- inject bits, verify rx_data, drive master ACK
//
// Delete this and start typing:
`,
      testbench:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;

  wire  sda;
  pullup pu(sda);

  logic       rst, mode, start, byte_done, done;
  logic [3:0] n_bytes;
  logic [7:0] tx_data, rx_data;
  logic       scl;
  logic       sda_tb;
  assign sda = sda_tb ? 1'bz : 1'b0;

  i2c_data_phase dut (
    .clk(clk), .rst(rst), .mode(mode), .start(start),
    .n_bytes(n_bytes), .tx_data(tx_data), .sda(sda),
    .scl(scl), .rx_data(rx_data), .byte_done(byte_done), .done(done)
  );

  task automatic send_byte(input logic [7:0] data, input logic ack_resp);
    integer i;
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = data[i] ? 1'b1 : 1'b0;
    end
    @(negedge scl); #1;
    sda_tb = ack_resp;
    @(posedge byte_done); #1;
    sda_tb = 1;
  endtask

  task automatic recv_byte(input logic [7:0] expected, input logic send_ack);
    integer i;
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = expected[i] ? 1'b1 : 1'b0;
    end
    @(negedge scl); #1;
    sda_tb = send_ack;
    @(posedge byte_done); #1;
    sda_tb = 1;
    if (rx_data === expected)
      \$display("PASS  received 0x%02h", expected);
    else
      \$display("FAIL  received 0x%02h (expected 0x%02h)", rx_data, expected);
  endtask

  initial begin
    \$display("=== Data Phase Test ===");
    rst = 0; sda_tb = 1; mode = 0; start = 0;
    n_bytes = 0; tx_data = 0;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    mode = 0; n_bytes = 4'd3;
    start = 1; @(posedge clk); #1; start = 0;
    tx_data = 8'hA1; send_byte(8'hA1, 1'b0);
    tx_data = 8'hB2; send_byte(8'hB2, 1'b0);
    tx_data = 8'hC3; send_byte(8'hC3, 1'b1);
    @(posedge done); #1;
    \$display("PASS  3 bytes transmitted");

    repeat(4) @(posedge clk); #1;

    mode = 1; n_bytes = 4'd2;
    start = 1; @(posedge clk); #1; start = 0;
    recv_byte(8'h55, 1'b0);
    recv_byte(8'hAA, 1'b1);
    @(posedge done); #1;
    \$display("PASS  2 bytes received");

    \$display("Data phase testbench works!");
    \$finish;
  end
endmodule`,
      expected: [
        'PASS  3 bytes transmitted',
        'PASS  2 bytes received',
        'Data phase testbench works!'
      ]
    },

    // ─────────────────────────────────────────────────────────────────────
    // L3 — Testing the Full Master Controller  (Tier 3)
    // ─────────────────────────────────────────────────────────────────────
    {
      id: 'i2ctb4l3',
      title: 'L3 — Testing the Full Master Controller',
      theory: `
<h2>Why full end-to-end master tests catch bugs that unit tests miss</h2>
<p>Unit tests for address phase and data phase check each stage in isolation. But real bugs often live in the <em>handoff</em> between stages: the master finishes sending the address ACK, then immediately misaligns its bit counter as the data phase begins. Linux I²C driver teams discovered this class of bug only when they ran a full write-then-read transaction at the top-level interface. This lesson shows you how to build that end-to-end test.</p>

<h2>Full I²C transaction timing diagram</h2>
<pre class="code-block">START  ADDR(7)  R/W  ACK  DATA(8)  ACK  DATA(8)  NACK  STOP
  |      |       |    |     |       |     |        |     |
SCL _  ‾‾ ...  ‾‾  ‾‾  ‾‾ ...  ‾‾  ‾‾ ...  ‾‾  ‾‾  ‾‾_ ‾‾
SDA  ↘0  a6..a0 rw  ↓0  d7..d0  ↓0  d7..d0  ‾   0↗1

  Write transaction: master drives all data bits, target ACKs each byte.
  Read transaction:  master drives address, target drives data bytes,
                     master ACKs all bytes except the last (master NACKs last).
</pre>

<h2>End-to-end write + read tasks</h2>
<p>You need two transaction-level tasks: one for a complete write and one for a complete read. Each wraps the address phase and data phase into a single call matching the top-level interface of <code>i2c_master</code>. The write task drives all data bits from the testbench side; the read task injects data bits from the target side and checks <code>data_out</code>. An <code>ack_err</code> output goes high if the target sends a NACK where an ACK was expected — test this path too.</p>

<pre class="code-block">// Write transaction task outline:
task automatic write_transaction(
  input logic [6:0] addr,
  input logic [7:0] data
);
  // 1. assert start, set addr, rw=0, tx_data=data
  // 2. wait for address ACK (sample addr_ack after 9 SCL cycles)
  // 3. drive data byte MSB-first, wait for done
  // 4. check ack_err === 0
endtask

// Read transaction task outline:
task automatic read_transaction(
  input logic [6:0] addr,
  input logic [7:0] inject_data,
  output logic [7:0] received
);
  // 1. assert start, set addr, rw=1
  // 2. wait for address ACK
  // 3. inject inject_data bits MSB-first on SDA while SCL high
  // 4. master NACKs last byte, check data_out === inject_data
endtask
</pre>

<table class="truth-table">
  <tr><th>Test</th><th>addr</th><th>rw</th><th>data</th><th>Expected result</th></tr>
  <tr><td>Write transaction</td><td>0x48</td><td>0</td><td>0xAB</td><td>done===1, ack_err===0</td></tr>
  <tr><td>Read transaction</td><td>0x48</td><td>1</td><td>injected 0xCD</td><td>data_out===0xCD, done===1</td></tr>
  <tr><td>NACK on address</td><td>0x50</td><td>0</td><td>—</td><td>ack_err===1</td></tr>
</table>

<h2>Before you code</h2>
<p>You are writing a testbench for <code>i2c_master</code>, the top-level I²C master controller. The testbench wraps both the address and data phases into write and read transaction tasks. It drives the SDA inout wire both to simulate a target ACK during the address phase and to inject data bytes during read transactions. A passing run prints three PASS lines followed by "Master controller testbench works!".</p>

<table class="truth-table">
  <tr><th>Port</th><th>Direction</th><th>Purpose</th></tr>
  <tr><td><code>clk</code></td><td>input logic</td><td>System clock for all FSM registers.</td></tr>
  <tr><td><code>rst</code></td><td>input logic</td><td>Synchronous active-low reset returning the master to IDLE.</td></tr>
  <tr><td><code>start</code></td><td>input logic</td><td>Pulse high to begin a new I²C transaction.</td></tr>
  <tr><td><code>addr</code></td><td>input logic [6:0]</td><td>7-bit target address sent during the address phase.</td></tr>
  <tr><td><code>rw</code></td><td>input logic</td><td>0 = write transaction, 1 = read transaction.</td></tr>
  <tr><td><code>tx_data</code></td><td>input logic [7:0]</td><td>Byte to transmit during the data phase (write mode).</td></tr>
  <tr><td><code>sda</code></td><td>inout wire</td><td>Bidirectional I²C data line shared between master and target.</td></tr>
  <tr><td><code>scl</code></td><td>output logic</td><td>I²C clock generated by the master.</td></tr>
  <tr><td><code>data_out</code></td><td>output logic [7:0]</td><td>Byte received during a read transaction.</td></tr>
  <tr><td><code>done</code></td><td>output logic</td><td>Pulses high for one cycle when the full transaction completes.</td></tr>
  <tr><td><code>ack_err</code></td><td>output logic</td><td>Goes high if a NACK was received where an ACK was required.</td></tr>
</table>

<p><strong>Ready?</strong> Switch to the Code tab and type the module. Stuck? Tap 💡 Show Hint for an annotated reference.</p>
      `,
      tasks: [
        'Code tab is blank — type every line.',
        'Declare tb with timescale, wire sda, pullup pu(sda), and 100 MHz clock',
        'Declare all DUT signals: rst, start, rw, addr [6:0], tx_data [7:0], scl, data_out [7:0], done, ack_err',
        'Declare logic sda_tb and assign sda = sda_tb ? 1\'bz : 1\'b0',
        'Instantiate i2c_master as dut connecting all ports',
        'Write task automatic write_transaction(addr, data): start the master, drive address ACK, drive data byte bits, wait for done, verify ack_err===0',
        'Write task automatic read_transaction(addr, inject_data): start master as read, ACK address, inject bits MSB-first on SDA, master NACKs last byte, verify data_out',
        'Test 1: write_transaction(7\'h48, 8\'hAB) — check done===1, ack_err===0',
        'Test 2: read_transaction(7\'h48, 8\'hCD) — check data_out===8\'hCD',
        'Test 3: start a write to 7\'h50 but inject NACK on address slot — check ack_err===1',
        'Print "Master controller testbench works!" and $finish',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 3 PASS lines should appear in the Output tab',
      ],
      hint:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;   // 100 MHz

  wire  sda;
  pullup pu(sda);

  logic       rst, start, rw, done, ack_err;
  logic [6:0] addr;
  logic [7:0] tx_data, data_out;
  logic       scl;

  logic sda_tb;  // 1=release(high via pullup), 0=pull low
  assign sda = sda_tb ? 1'bz : 1'b0;

  i2c_master dut (
    .clk     (clk),
    .rst     (rst),
    .start   (start),
    .addr    (addr),
    .rw      (rw),
    .tx_data (tx_data),
    .sda     (sda),
    .scl     (scl),
    .data_out(data_out),
    .done    (done),
    .ack_err (ack_err)
  );

  // Helper: wait for N SCL rising edges
  task automatic wait_scl_edges(input integer n);
    integer i;
    for (i = 0; i < n; i++) @(posedge scl);
  endtask

  // write_transaction: drive address ACK, drive data bits, check done
  task automatic write_transaction(
    input logic [6:0] a,
    input logic [7:0] data
  );
    addr = a; rw = 0; tx_data = data; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    // wait 8 address + 1 R/W bit, then ACK on 9th SCL cycle
    wait_scl_edges(9);
    @(negedge scl); #1; sda_tb = 0;  // target ACKs address
    @(posedge scl);  #1; sda_tb = 1; // release after ACK sampled
    // wait 8 data bits + 1 ACK
    wait_scl_edges(8);
    @(negedge scl); #1; sda_tb = 0;  // target ACKs data
    @(posedge scl);  #1; sda_tb = 1;
    @(posedge done); #1;
  endtask

  // read_transaction: ACK address, inject data bits MSB-first, master NACKs last byte
  task automatic read_transaction(
    input  logic [6:0] a,
    input  logic [7:0] inject
  );
    integer i;
    addr = a; rw = 1; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    // address + R/W (9 clocks)
    wait_scl_edges(9);
    @(negedge scl); #1; sda_tb = 0;  // target ACKs address
    @(posedge scl);  #1; sda_tb = 1;
    // inject 8 data bits MSB-first: target drives SDA while SCL is low
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = inject[i] ? 1'b1 : 1'b0;
    end
    @(posedge scl); #1; sda_tb = 1;  // release for master NACK cycle
    @(posedge done); #1;
  endtask

  initial begin
    \$display("=== Master Controller Test ===");
    rst = 0; sda_tb = 1; start = 0; addr = 0; rw = 0; tx_data = 0;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    // Test 1: write transaction
    write_transaction(7'h48, 8'hAB);
    if (done === 1 && ack_err === 0)
      \$display("PASS  write transaction complete");
    else
      \$display("FAIL  write: done=%0b ack_err=%0b", done, ack_err);

    repeat(4) @(posedge clk); #1;

    // Test 2: read transaction
    read_transaction(7'h48, 8'hCD);
    if (data_out === 8'hCD)
      \$display("PASS  read transaction complete");
    else
      \$display("FAIL  read: data_out=0x%02h (expected 0xcd)", data_out);

    repeat(4) @(posedge clk); #1;

    // Test 3: NACK on address -> ack_err
    addr = 7'h50; rw = 0; tx_data = 8'h00; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    wait_scl_edges(9);
    // do NOT pull SDA low: NACK (sda released via pullup = 1)
    @(posedge done); #1;
    if (ack_err === 1)
      \$display("PASS  NACK on address: ack_err=1");
    else
      \$display("FAIL  ack_err=%0b (expected 1)", ack_err);

    \$display("Master controller testbench works!");
    \$finish;
  end
endmodule`,
      design:
`// Build the i2c_master testbench here. See Theory for the full spec.
//
// Signals: wire sda + pullup; logic sda_tb; all DUT ports
//
// Tasks:
//   write_transaction(addr, data) -- drive address ACK, data bits, check done
//   read_transaction(addr, inject) -- inject target data bits, check data_out
//
// Three tests: write 0xAB to 0x48, read 0xCD from 0x48, NACK on 0x50
`,
      testbench:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;

  wire  sda;
  pullup pu(sda);

  logic       rst, start, rw, done, ack_err;
  logic [6:0] addr;
  logic [7:0] tx_data, data_out;
  logic       scl;
  logic       sda_tb;
  assign sda = sda_tb ? 1'bz : 1'b0;

  i2c_master dut (
    .clk(clk), .rst(rst), .start(start), .addr(addr),
    .rw(rw), .tx_data(tx_data), .sda(sda), .scl(scl),
    .data_out(data_out), .done(done), .ack_err(ack_err)
  );

  task automatic wait_scl_edges(input integer n);
    integer i;
    for (i = 0; i < n; i++) @(posedge scl);
  endtask

  task automatic write_transaction(input logic [6:0] a, input logic [7:0] data);
    addr = a; rw = 0; tx_data = data; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    wait_scl_edges(9);
    @(negedge scl); #1; sda_tb = 0;
    @(posedge scl);  #1; sda_tb = 1;
    wait_scl_edges(8);
    @(negedge scl); #1; sda_tb = 0;
    @(posedge scl);  #1; sda_tb = 1;
    @(posedge done); #1;
  endtask

  task automatic read_transaction(input logic [6:0] a, input logic [7:0] inject);
    integer i;
    addr = a; rw = 1; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    wait_scl_edges(9);
    @(negedge scl); #1; sda_tb = 0;
    @(posedge scl);  #1; sda_tb = 1;
    for (i = 7; i >= 0; i--) begin
      @(negedge scl); #1;
      sda_tb = inject[i] ? 1'b1 : 1'b0;
    end
    @(posedge scl); #1; sda_tb = 1;
    @(posedge done); #1;
  endtask

  initial begin
    \$display("=== Master Controller Test ===");
    rst = 0; sda_tb = 1; start = 0; addr = 0; rw = 0; tx_data = 0;
    repeat(2) @(posedge clk); #1;
    rst = 1;

    write_transaction(7'h48, 8'hAB);
    if (done === 1 && ack_err === 0)
      \$display("PASS  write transaction complete");
    else
      \$display("FAIL  write: done=%0b ack_err=%0b", done, ack_err);

    repeat(4) @(posedge clk); #1;

    read_transaction(7'h48, 8'hCD);
    if (data_out === 8'hCD)
      \$display("PASS  read transaction complete");
    else
      \$display("FAIL  read: data_out=0x%02h", data_out);

    repeat(4) @(posedge clk); #1;

    addr = 7'h50; rw = 0; tx_data = 8'h00; sda_tb = 1;
    start = 1; @(posedge clk); #1; start = 0;
    wait_scl_edges(9);
    @(posedge done); #1;
    if (ack_err === 1)
      \$display("PASS  NACK on address: ack_err=1");
    else
      \$display("FAIL  ack_err=%0b (expected 1)", ack_err);

    \$display("Master controller testbench works!");
    \$finish;
  end
endmodule`,
      expected: [
        'PASS  write transaction complete',
        'PASS  read transaction complete',
        'Master controller testbench works!'
      ]
    }

  ]
});
