(window.CURRICULUM_MODULES = window.CURRICULUM_MODULES || []).push({
  id: 'spi_long1',
  title: 'SPI Protocol & Signal Definitions',
  icon: '🔌',
  level: 'intermediate',
  lessons: [

    // ─────────────────────────────────────────────────────────────────────────
    // L1 — SPI Signal Anatomy (Tier 1)
    // ─────────────────────────────────────────────────────────────────────────
    {
      id: 'spi_long1l1',
      title: 'L1 — MOSI, MISO, SCK, SS_n',

      theory: `
<h2>The Four Wires of SPI</h2>
<p>
  Serial Peripheral Interface (SPI) uses exactly four signals between a master
  and one slave. Unlike I²C there is no shared address bus — the master selects
  a slave by asserting a dedicated <strong>Slave Select</strong> line low, then
  clocks bits in and out simultaneously on the two data wires.
</p>

<pre class="code-block">
  MASTER                        SLAVE
  ──────                        ─────
  MOSI ─────────────────────►  MOSI   (data out of master, into slave)
  MISO ◄─────────────────────  MISO   (data out of slave, into master)
  SCK  ─────────────────────►  SCK    (clock, always driven by master)
  SS_n ─────────────────────►  SS_n   (active-LOW chip select)
</pre>

<p>
  <strong>MOSI</strong> — Master-Out Slave-In. The master drives this line;
  the slave reads it.<br>
  <strong>MISO</strong> — Master-In Slave-Out. The slave drives this line;
  the master reads it.<br>
  <strong>SCK</strong> — Serial Clock. Always generated by the master. The slave
  has no clock of its own — it reacts to SCK edges.<br>
  <strong>SS_n</strong> — Slave Select, active-LOW. While SS_n is HIGH the slave
  ignores MOSI and leaves MISO floating (tri-state).
</p>

<h3>Naming in this controller</h3>
<p>
  In the SPI master RTL you are about to build, the signals are named:
  <code>spi_mosi_o</code>, <code>spi_miso_i</code>, <code>spi_sck_o</code>,
  and <code>spi_csn_o[N:0]</code> (one CS line per slave, N up to 7).
  The <code>_o</code>/<code>_i</code> suffix follows the AMBA pad-naming
  convention: outputs leave the chip, inputs arrive at the chip.
</p>

<h3>What you will build</h3>
<p>
  A tiny module called <code>spi_signals</code> that uses <code>assign</code>
  statements to connect internal signals to the four SPI pads. This chapter
  is conceptual — the real routing logic lives in later chapters — but getting
  the signal directions right is the first thing any RTL engineer checks.
</p>

<table class="truth-table">
  <tr><th>Port</th><th>Direction</th><th>Active level</th><th>Source</th></tr>
  <tr><td><code>mosi</code></td><td>output</td><td>n/a</td><td>tx_shift[MSB]</td></tr>
  <tr><td><code>miso</code></td><td>input</td><td>n/a</td><td>slave drives</td></tr>
  <tr><td><code>sck</code></td><td>output</td><td>see CPOL</td><td>clock divider</td></tr>
  <tr><td><code>ss_n</code></td><td>output</td><td>LOW = asserted</td><td>CS controller</td></tr>
</table>

<p><strong>Ready?</strong> Switch to the Code tab and type the module.
Stuck? Tap 💡 Show Hint for an annotated reference.</p>
`,

      tasks: [
        'Code tab is blank — type every line.',
        '── Line 1 ──  module spi_signals (   ← open paren, no semicolon',
        '── Line 2 ──  input  logic tx_bit,   ← bit to send; comma after type',
        '── Line 3 ──  input  logic miso_in,  ← bit arriving from slave',
        '── Line 4 ──  input  logic sck_int,  ← internal clock toggle',
        '── Line 5 ──  input  logic cs_n_raw, ← raw CS from CS controller',
        '── Line 6 ──  output logic mosi,     ← pad: master-out',
        '── Line 7 ──  output logic miso,     ← pad: master-in (alias for miso_in)',
        '── Line 8 ──  output logic sck,      ← pad: serial clock',
        '── Line 9 ──  output logic ss_n      ← pad: chip select, NO comma on last port',
        '── Line 10 ── );                     ← close paren + semicolon',
        '── Line 11 ── assign mosi = tx_bit;',
        '── Line 12 ── assign miso = miso_in;',
        '── Line 13 ── assign sck  = sck_int;',
        '── Line 14 ── assign ss_n = cs_n_raw;',
        '── Line 15 ── endmodule',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 4 PASS lines should appear in the Output tab',
      ],

      hint:
`module spi_signals (
  input  logic tx_bit,    // bit the shift register wants to send
  input  logic miso_in,   // bit that arrived from the slave pad
  input  logic sck_int,   // internal SCK toggle from the clock divider
  input  logic cs_n_raw,  // CS polarity-corrected signal (active-low)
  output logic mosi,      // SPI pad: Master-Out Slave-In
  output logic miso,      // SPI pad: Master-In Slave-Out (alias)
  output logic sck,       // SPI pad: Serial Clock
  output logic ss_n       // SPI pad: Slave Select, active-LOW (note: no comma)
);

  assign mosi = tx_bit;    // what master transmits → the wire
  assign miso = miso_in;   // what arrived on the pad → readable internally
  assign sck  = sck_int;   // clock divider output → pad
  assign ss_n = cs_n_raw;  // CS controller output → pad (already active-low)

endmodule`,

      design:
`// Type the spi_signals module here.
// Read Theory first — it explains the four SPI pad directions.
//
// Ports:
//   input  logic tx_bit    — bit to send (from shift register)
//   input  logic miso_in   — bit received from slave pad
//   input  logic sck_int   — clock toggle from clock divider
//   input  logic cs_n_raw  — chip select (already active-low)
//   output logic mosi      — SPI MOSI pad
//   output logic miso      — SPI MISO pad (alias for miso_in)
//   output logic sck       — SPI SCK pad
//   output logic ss_n      — SPI SS_n pad
//
// Each output is a direct assign from its corresponding input.
//
// Delete this and start typing:
`,

      testbench:
`\`timescale 1ns/1ps
module tb;
  logic tx_bit, miso_in, sck_int, cs_n_raw;
  logic mosi, miso, sck, ss_n;

  spi_signals dut (
    .tx_bit   (tx_bit),
    .miso_in  (miso_in),
    .sck_int  (sck_int),
    .cs_n_raw (cs_n_raw),
    .mosi     (mosi),
    .miso     (miso),
    .sck      (sck),
    .ss_n     (ss_n)
  );

  task automatic check_wire(
    input string name,
    input logic  got,
    input logic  exp
  );
    if (got === exp)
      $display("PASS  %s: %0b", name, got);
    else
      $display("FAIL  %s: got=%0b expected=%0b", name, got, exp);
  endtask

  initial begin
    $display("=== SPI Signal Anatomy ===");

    // MOSI follows tx_bit
    tx_bit = 1; miso_in = 0; sck_int = 0; cs_n_raw = 1; #5;
    check_wire("mosi", mosi, 1'b1);

    tx_bit = 0; #5;
    check_wire("mosi when tx=0", mosi, 1'b0);

    // MISO follows miso_in
    miso_in = 1; #5;
    check_wire("miso", miso, 1'b1);

    // SCK follows sck_int
    sck_int = 1; #5;
    check_wire("sck", sck, 1'b1);

    // SS_n follows cs_n_raw (LOW = asserted)
    cs_n_raw = 0; #5;
    check_wire("ss_n asserted", ss_n, 1'b0);

    $display("SPI signal wiring complete!");
    $finish;
  end
endmodule`,

      expected: [
        'PASS  mosi: 1',
        'PASS  ss_n asserted: 0',
        'SPI signal wiring complete!',
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────
    // L2 — Full-Duplex Exchange (Tier 1)
    // ─────────────────────────────────────────────────────────────────────────
    {
      id: 'spi_long1l2',
      title: 'L2 — Full-Duplex Shift Register',

      theory: `
<h2>SPI Is a Circular Shift Register</h2>
<p>
  The most important insight in SPI is this: the master and slave each hold
  one shift register, and those two registers are <strong>wired end-to-end
  in a ring</strong>. Every clock edge rotates both registers simultaneously
  — one bit falls off the master's MSB (MOSI) and lands in the slave's LSB,
  while one bit falls off the slave's MSB (MISO) and lands in the master's LSB.
  After 8 edges both registers have exchanged their entire contents.
</p>

<pre class="code-block">
  MASTER tx_shift             SLAVE tx_shift
  ┌──┬──┬──┬──┬──┬──┬──┬──┐  ┌──┬──┬──┬──┬──┬──┬──┬──┐
  │7 │6 │5 │4 │3 │2 │1 │0 │  │7 │6 │5 │4 │3 │2 │1 │0 │
  └──┴──┴──┴──┴──┴──┴──┴──┘  └──┴──┴──┴──┴──┴──┴──┴──┘
      │ ◄── SCK edge ──►  │        │
      └────── MOSI ───────►        │
              MISO ◄───────────────┘
</pre>

<p>
  In RTL the shift register update on each clock edge looks like this:
</p>
<pre class="code-block">
  // Both happen in the SAME always_ff block, on the SAME edge:
  tx_shift &lt;= {tx_shift[6:0], 1'b0};          // shift left, MSB goes to MOSI
  rx_shift &lt;= {rx_shift[6:0], miso_in};        // shift left, MISO enters LSB
</pre>

<h3>The slave-echo pattern (loopback test)</h3>
<p>
  In hardware-bring-up you often wire MISO = MOSI on the PCB to verify the
  master works before connecting a real slave. This is called a <em>loopback</em>.
  After 8 shift cycles with loopback active, the master's RX register should
  contain exactly what was loaded into its TX register.
</p>

<h3>What you will build</h3>
<p>
  A module called <code>spi_frame</code> with an 8-bit TX shift register and
  an 8-bit RX shift register. On each active clock edge the module shifts
  both registers one position. A combinational <code>assign</code> drives
  MOSI from the MSB of the TX register so the new value is always on the wire
  before the clock edge hits.
</p>

<p><strong>Ready?</strong> Switch to the Code tab and type the module.
Stuck? Tap 💡 Show Hint for an annotated reference.</p>
`,

      tasks: [
        'Code tab is blank — type every line.',
        '── Line 1 ──  module spi_frame (',
        '── Line 2 ──  input  logic       clk,',
        '── Line 3 ──  input  logic       rst_n,     ← active-low async reset',
        '── Line 4 ──  input  logic       load,      ← parallel-load TX data',
        '── Line 5 ──  input  logic       shift_en,  ← one pulse per SCK edge',
        '── Line 6 ──  input  logic [7:0] tx_data,   ← word to transmit',
        '── Line 7 ──  input  logic       miso_in,   ← bit from slave',
        '── Line 8 ──  output logic       mosi_out,  ← bit to slave',
        "── Line 9 ──  output logic [7:0] rx_data    ← captured word, NO comma",
        '── Line 10 ── );',
        '── Line 11 ── logic [7:0] tx_shift;   ← internal TX shift register',
        '── Line 12 ── logic [7:0] rx_shift;   ← internal RX shift register',
        '── Line 13 ── Declare the always_ff block with posedge clk and negedge rst_n',
        "── Line 14 ── In reset: tx_shift <= 8'b0; rx_shift <= 8'b0;",
        '── Line 15 ── On load: tx_shift <= tx_data;',
        '── Line 16 ── On shift_en: shift tx_shift left (MSB goes to MOSI)',
        '── Line 17 ── On shift_en: shift rx_shift left, miso_in enters bit [0]',
        '── Line 18 ── assign mosi_out = tx_shift[7];   ← MSB is always on the wire',
        '── Line 19 ── assign rx_data  = rx_shift;',
        '── Line 20 ── endmodule',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 3 PASS lines should appear in the Output tab',
      ],

      hint:
`module spi_frame (
  input  logic       clk,
  input  logic       rst_n,      // active-low asynchronous reset
  input  logic       load,       // parallel-load strobe
  input  logic       shift_en,   // one pulse per SCK edge
  input  logic [7:0] tx_data,    // word to transmit
  input  logic       miso_in,    // serial bit from slave
  output logic       mosi_out,   // serial bit to slave
  output logic [7:0] rx_data     // parallel received word
);

  logic [7:0] tx_shift;   // TX shift register
  logic [7:0] rx_shift;   // RX shift register

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tx_shift <= 8'b0;   // clear on reset
      rx_shift <= 8'b0;
    end else if (load) begin
      tx_shift <= tx_data;  // parallel load — happens in LOAD state
    end else if (shift_en) begin
      tx_shift <= {tx_shift[6:0], 1'b0};    // shift left; MSB leaves via mosi_out
      rx_shift <= {rx_shift[6:0], miso_in}; // shift left; MISO enters at bit 0
    end
  end

  // MOSI is always the current MSB — combinational, not registered.
  // This ensures MOSI is valid BEFORE the next SCK edge.
  assign mosi_out = tx_shift[7];
  assign rx_data  = rx_shift;

endmodule`,

      design:
`// Type the spi_frame module here.
// Read Theory first — it explains the circular shift register model.
//
// Ports:
//   input  logic       clk       — system clock
//   input  logic       rst_n     — active-low async reset
//   input  logic       load      — load tx_data into tx_shift
//   input  logic       shift_en  — one pulse per SCK edge
//   input  logic [7:0] tx_data   — word to send
//   input  logic       miso_in   — serial bit from slave
//   output logic       mosi_out  — serial bit to slave (= tx_shift[7])
//   output logic [7:0] rx_data   — received word (= rx_shift)
//
// Internal registers: tx_shift[7:0], rx_shift[7:0]
//
// Delete this and start typing:
`,

      testbench:
`\`timescale 1ns/1ps
module tb;
  logic clk = 0;
  always #5 clk = ~clk;  // 100 MHz

  logic       rst_n, load, shift_en, miso_in;
  logic       mosi_out;
  logic [7:0] tx_data, rx_data;

  spi_frame dut (
    .clk      (clk),
    .rst_n    (rst_n),
    .load     (load),
    .shift_en (shift_en),
    .tx_data  (tx_data),
    .miso_in  (miso_in),
    .mosi_out (mosi_out),
    .rx_data  (rx_data)
  );

  // Loopback: slave echoes every bit master sends
  assign miso_in = mosi_out;

  // Perform one 8-bit loopback transfer and check result
  task automatic do_transfer(input logic [7:0] data, input logic [7:0] exp);
    integer i;
    // Load word
    load = 1; tx_data = data;
    @(posedge clk); #1;
    load = 0;
    // 8 shift pulses
    for (i = 0; i < 8; i++) begin
      shift_en = 1;
      @(posedge clk); #1;
      shift_en = 0;
    end
    // Check
    if (rx_data === exp)
      $display("PASS  tx=0x%02h -> rx=0x%02h", data, rx_data);
    else
      $display("FAIL  tx=0x%02h -> rx=0x%02h (expected 0x%02h)", data, rx_data, exp);
  endtask

  initial begin
    $display("=== SPI Full-Duplex Loopback ===");
    rst_n = 0; load = 0; shift_en = 0; tx_data = 0;
    repeat(2) @(posedge clk); rst_n = 1;

    do_transfer(8'hA5, 8'hA5);   // loopback: rx should equal tx
    do_transfer(8'hFF, 8'hFF);   // all-ones
    do_transfer(8'h00, 8'h00);   // all-zeros

    $display("Full-duplex loopback works!");
    $finish;
  end
endmodule`,

      expected: [
        'PASS  tx=0xa5 -> rx=0xa5',
        'PASS  tx=0xff -> rx=0xff',
        'Full-duplex loopback works!',
      ],
    },

    // ─────────────────────────────────────────────────────────────────────────
    // L3 — CPOL/CPHA Mode Decoder (Tier 2)
    // ─────────────────────────────────────────────────────────────────────────
    {
      id: 'spi_long1l3',
      title: 'L3 — CPOL/CPHA Mode Decoder',

      theory: `
<h2>The Four SPI Modes</h2>
<p>
  SPI has no universal standard for which clock edge carries data. Two
  configuration bits let you choose:
</p>
<ul>
  <li><strong>CPOL</strong> (Clock POLarity) — sets the idle level of SCK when
    no transfer is active. CPOL=0 → SCK idles LOW; CPOL=1 → SCK idles HIGH.</li>
  <li><strong>CPHA</strong> (Clock PHAse) — sets whether data is
    <em>launched</em> on the first active edge or the second.
    CPHA=0 → sample on first edge; CPHA=1 → sample on second edge.</li>
</ul>
<p>
  Combined, they produce four <em>modes</em>. Master and slave must use
  the same mode or the data will be garbage.
</p>

<table class="truth-table">
  <tr>
    <th>Mode</th><th>CPOL</th><th>CPHA</th>
    <th>SCK idle</th><th>MOSI launched on</th><th>MISO sampled on</th>
  </tr>
  <tr><td>0</td><td>0</td><td>0</td><td>LOW</td><td>Falling edge</td><td>Rising edge (1st)</td></tr>
  <tr><td>1</td><td>0</td><td>1</td><td>LOW</td><td>Rising edge</td><td>Falling edge (2nd)</td></tr>
  <tr><td>2</td><td>1</td><td>0</td><td>HIGH</td><td>Rising edge</td><td>Falling edge (1st)</td></tr>
  <tr><td>3</td><td>1</td><td>1</td><td>HIGH</td><td>Falling edge</td><td>Rising edge (2nd)</td></tr>
</table>

<p>
  There is a useful pattern hidden in the table:
</p>
<pre class="code-block">
  idle_level     = cpol              // CPOL IS the idle level
  sample_on_rise = !(cpol ^ cpha)   // sample on rising edge?
  launch_on_rise =  (cpol ^ cpha)   // launch on rising edge?
</pre>
<p>
  This means a single XOR gate between CPOL and CPHA tells you whether
  MOSI is launched on the rising or falling edge. Your decoder will implement
  exactly this truth table using <code>always_comb</code> and <code>case</code>.
</p>

<h3>The most common mistake</h3>
<p>
  Many engineers memorise "Mode 0 = most common, rising edge samples" and
  assume that means <em>all</em> ADCs and DACs use Mode 0. They don't.
  Always check the slave's datasheet for its mode before wiring up SCK.
  This one mistake accounts for more SPI bring-up failures than any other cause.
</p>

<h3>What you will build</h3>
<p>
  A combinational decoder module called <code>spi_mode_decode</code>. It takes
  <code>cpol</code> and <code>cpha</code> as inputs and outputs the three
  derived signals above. Use an <code>always_comb</code> block with
  <code>case ({cpol, cpha})</code>.
</p>

<p><strong>Ready?</strong> Switch to the Code tab and type the module.
Stuck? Tap 💡 Show Hint for an annotated reference.</p>
`,

      tasks: [
        'Code tab is blank — type every line.',
        '── Line 1 ──  module spi_mode_decode (   ← module header',
        '── Line 2 ──  input  logic cpol,          ← clock polarity bit',
        '── Line 3 ──  input  logic cpha,          ← clock phase bit',
        '── Line 4 ──  output logic idle_level,    ← SCK level when CS is deasserted',
        '── Line 5 ──  output logic launch_on_rise, ← 1 = MOSI changes on SCK rising edge',
        '── Line 6 ──  output logic sample_on_rise  ← 1 = MISO sampled on SCK rising edge',
        '── Line 7 ──  );',
        '── Line 8 ──  Declare an always_comb block',
        '── Line 9 ──  Inside it: assign idle_level = cpol  (CPOL is the idle level directly)',
        '── Line 10 ── Write case ({cpol, cpha}) covering all four 2-bit combinations',
        "── Line 11 ── Mode 0 (2'b00): launch_on_rise=0, sample_on_rise=1",
        "── Line 12 ── Mode 1 (2'b01): launch_on_rise=1, sample_on_rise=0",
        "── Line 13 ── Mode 2 (2'b10): launch_on_rise=1, sample_on_rise=0",
        "── Line 14 ── Mode 3 (2'b11): launch_on_rise=0, sample_on_rise=1",
        '── Line 15 ── Add a default case to avoid latches',
        '── Line 16 ── endmodule',
        'Using Verilator: open ⚙ Options and set Timing Mode to --no-timing before running',
        'Hit Run — all 4 PASS lines should appear in the Output tab',
      ],

      hint:
`module spi_mode_decode (
  input  logic cpol,
  input  logic cpha,
  output logic idle_level,      // SCK level when idle
  output logic launch_on_rise,  // 1 = MOSI updated on rising SCK edge
  output logic sample_on_rise   // 1 = MISO captured on rising SCK edge
);

  always_comb begin
    idle_level = cpol;  // CPOL is the idle level by definition

    case ({cpol, cpha})
      2'b00: begin  // Mode 0 — most common (CPOL=0, CPHA=0)
        launch_on_rise = 1'b0;  // MOSI changes on falling edge
        sample_on_rise = 1'b1;  // MISO sampled on rising edge
      end
      2'b01: begin  // Mode 1
        launch_on_rise = 1'b1;  // MOSI changes on rising edge
        sample_on_rise = 1'b0;  // MISO sampled on falling edge
      end
      2'b10: begin  // Mode 2
        launch_on_rise = 1'b1;  // MOSI changes on rising edge
        sample_on_rise = 1'b0;  // MISO sampled on falling edge
      end
      2'b11: begin  // Mode 3
        launch_on_rise = 1'b0;  // MOSI changes on falling edge
        sample_on_rise = 1'b1;  // MISO sampled on rising edge
      end
      default: begin
        launch_on_rise = 1'b0;
        sample_on_rise = 1'b1;
      end
    endcase
  end

endmodule`,

      design:
`// Type the spi_mode_decode module here. See Theory for the mode table.
//
// Ports:
//   input  logic cpol           — clock polarity
//   input  logic cpha           — clock phase
//   output logic idle_level     — SCK level when not transferring
//   output logic launch_on_rise — 1 if MOSI updates on SCK rising edge
//   output logic sample_on_rise — 1 if MISO is sampled on SCK rising edge
//
// Use always_comb + case({cpol, cpha}) to match the 4-row truth table.
//
// Delete this and start typing:
`,

      testbench:
`\`timescale 1ns/1ps
module tb;
  logic cpol, cpha;
  logic idle_level, launch_on_rise, sample_on_rise;

  spi_mode_decode dut (
    .cpol           (cpol),
    .cpha           (cpha),
    .idle_level     (idle_level),
    .launch_on_rise (launch_on_rise),
    .sample_on_rise (sample_on_rise)
  );

  task automatic check_mode(
    input logic cp, ch,
    input logic exp_idle, exp_launch, exp_sample
  );
    cpol = cp; cpha = ch; #5;
    if (idle_level === exp_idle &&
        launch_on_rise === exp_launch &&
        sample_on_rise === exp_sample)
      $display("PASS  Mode %0d (cpol=%0b cpha=%0b): idle=%0b launch_rise=%0b sample_rise=%0b",
               {cp,ch}, cp, ch, idle_level, launch_on_rise, sample_on_rise);
    else
      $display("FAIL  Mode %0d (cpol=%0b cpha=%0b): got idle=%0b launch=%0b sample=%0b",
               {cp,ch}, cp, ch, idle_level, launch_on_rise, sample_on_rise);
  endtask

  initial begin
    $display("=== CPOL/CPHA Mode Decoder ===");
    //              cpol cpha  idle  launch sample_rise
    check_mode(0,0,  1'b0, 1'b0, 1'b1);  // Mode 0: idle=0, launch-fall, sample-rise
    check_mode(0,1,  1'b0, 1'b1, 1'b0);  // Mode 1: idle=0, launch-rise, sample-fall
    check_mode(1,0,  1'b1, 1'b1, 1'b0);  // Mode 2: idle=1, launch-rise, sample-fall
    check_mode(1,1,  1'b1, 1'b0, 1'b1);  // Mode 3: idle=1, launch-fall, sample-rise
    $display("All 4 SPI modes verified!");
    $finish;
  end
endmodule`,

      expected: [
        'PASS  Mode 0',
        'PASS  Mode 3',
        'All 4 SPI modes verified!',
      ],
    },

  ]
});
